title: Oil Is Bliss
author: Gustavo Varela
email: my@email.com
description: > # this means to ignore newlines until "baseurl:"
  Tibetan Medicine, Essential Oils and Aromatherapy experts. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.

# social links
twitter_username: oilsisbliss
github_username:  oilisbliss

show_excerpts: true # set to false to remove excerpts on the homepage

theme: minima
